tunnel: bb7ece59-8680-4310-9437-232f862e2773
credentials-file: /Users/cliang/.cloudflared/bb7ece59-8680-4310-9437-232f862e2773.json

ingress:
  - hostname: argocd.3ai-talk.org
    service: http://localhost:8080
  - hostname: frontend.3ai-talk.org
    service: http://127.0.0.2:80
  - hostname: keycloak.3ai-talk.org
    service: http://localhost:8880
  - hostname: prometheus.3ai-talk.org
    service: http://localhost:19090
  - hostname: grafana.3ai-talk.org
    service: http://localhost:3001
  - hostname: webhook.3ai-talk.org
    service: http://127.0.0.1:7443
  - hostname: vault.3ai-talk.org
    service: http://localhost:18080
  - service: http_status:404
