admissionWebhooks:
  enabled: false

prometheusOperator:
  tls:
    enabled: false

defaultRules:
  rules:
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    alertmanager: false
    configReloaders: false

grafana:
  enabled: true
  additionalDataSources:
    - name: prometheus-acg
      type: prometheus
      uid: P5A1115AEDF367D43
      url: http://acg-kube-prometheus-stack-prometheus.monitoring:9090/
      access: proxy
      jsonData:
        httpMethod: POST
        timeInterval: 30s
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 192Mi
      cpu: 200m
  service:
    type: NodePort
    nodePort: 30030
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Viewer

alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
      limits:
        memory: 64Mi
        cpu: 50m
  configSecret: alertmanager-smtp-secret
  service:
    type: NodePort
    nodePort: 30093

prometheus:
  prometheusSpec:
    externalLabels:
      cluster: ubuntu-k3s
    retention: 2h
    resources:
      requests:
        memory: 256Mi
        cpu: 50m
      limits:
        memory: 512Mi
        cpu: 200m
    additionalScrapeConfigs:
      - job_name: istiod
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: [istio-system]
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: istiod
      - job_name: pushgateway
        honor_labels: true
        static_configs:
          - targets: ['prometheus-pushgateway.monitoring:9091']
  service:
    type: NodePort
    nodePort: 30090

kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
coreDns:
  enabled: false
kubeProxy:
  enabled: false
