defaultRules:
  rules:
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    configReloaders: false

prometheus:
  prometheusSpec:
    scrapeInterval: 60s
    evaluationInterval: 60s
    retention: 3d
    retentionSize: 8GB
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 25Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1500m
    additionalScrapeConfigs:
      - job_name: istiod
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: [istio-system]
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: istiod
      - job_name: federate-acg
        scrape_interval: 60s
        honor_labels: true
        metrics_path: /federate
        params:
          match[]:
            - '{job=~"node-exporter|kubelet|kube-state-metrics|istiod|envoy"}'
        static_configs:
          - targets:
              - 'host.internal:19090'
            labels:
              cluster: acg

grafana:
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password
  resources:
    requests:
      memory: 64Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  additionalDataSources:
    - name: acg-prometheus
      type: prometheus
      url: http://host.internal:19090
      access: proxy
      jsonData:
        timeInterval: 30s
    - name: Loki
      uid: loki
      type: loki
      url: http://loki-gateway.monitoring.svc.cluster.local
      access: proxy
      jsonData: {}

alertmanager:
  enabled: true
  alertmanagerSpec:
    alertmanagerConfigMatcherStrategy:
      type: None
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
      limits:
        memory: 64Mi
        cpu: 50m
  configSecret: alertmanager-smtp-secret

kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
coreDns:
  enabled: false
kubeProxy:
  enabled: false
