defaultRules:
  rules:
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    configReloaders: false

prometheus:
  prometheusSpec:
    retention: 7d
    retentionSize: 1800MB
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 2Gi
        cpu: 500m
    additionalScrapeConfigs:
      - job_name: istiod
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: [istio-system]
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: istiod
      - job_name: federate-acg
        scrape_interval: 30s
        honor_labels: true
        metrics_path: /federate
        params:
          match[]:
            - '{job=~"node-exporter|kubelet|kube-state-metrics|istiod|envoy"}'
        static_configs:
          - targets:
              - 'host.internal:19090'
            labels:
              cluster: acg

grafana:
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 192Mi
      cpu: 200m
  additionalDataSources:
    - name: acg-prometheus
      type: prometheus
      url: http://host.internal:19090
      access: proxy
      jsonData:
        timeInterval: 30s
    - name: Loki
      uid: loki
      type: loki
      url: http://hub-loki-gateway.monitoring.svc.cluster.local
      access: proxy
      jsonData: {}

alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
      limits:
        memory: 64Mi
        cpu: 50m
  configSecret: alertmanager-smtp-secret

kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
coreDns:
  enabled: false
kubeProxy:
  enabled: false
