export K3S_INSTALL_DIR="${K3S_INSTALL_DIR:-/usr/local/bin}"
export K3S_DATA_DIR="${K3S_DATA_DIR:-/var/lib/rancher/k3s}"
export K3S_CONFIG_DIR="${K3S_CONFIG_DIR:-/etc/rancher/k3s}"
export K3S_CONFIG_FILE="${K3S_CONFIG_FILE:-${K3S_CONFIG_DIR}/config.yaml}"
export K3S_KUBECONFIG_PATH="${K3S_KUBECONFIG_PATH:-${K3S_CONFIG_DIR}/k3s.yaml}"
export K3S_SERVICE_NAME="${K3S_SERVICE_NAME:-k3s}"
export K3S_SERVICE_FILE="${K3S_SERVICE_FILE:-/etc/systemd/system/${K3S_SERVICE_NAME}.service}"
export K3S_MANIFEST_DIR="${K3S_MANIFEST_DIR:-${K3S_DATA_DIR}/server/manifests}"
export K3S_LOCAL_STORAGE="${K3S_LOCAL_STORAGE:-${JENKINS_HOME_PATH:-${SCRIPT_DIR}/storage/jenkins_home}}"

# Ingress forwarding configuration
export K3S_INGRESS_FORWARD_ENABLED="${K3S_INGRESS_FORWARD_ENABLED:-1}"
export K3S_INGRESS_FORWARD_HTTP_PORT="${K3S_INGRESS_FORWARD_HTTP_PORT:-80}"
export K3S_INGRESS_FORWARD_HTTPS_PORT="${K3S_INGRESS_FORWARD_HTTPS_PORT:-443}"
export K3S_INGRESS_SERVICE_NAME="${K3S_INGRESS_SERVICE_NAME:-k3s-ingress-forward}"
export K3S_INGRESS_SERVICE_FILE="${K3S_INGRESS_SERVICE_FILE:-/etc/systemd/system/${K3S_INGRESS_SERVICE_NAME}.service}"

# Ubuntu k3s remote access
export UBUNTU_K3S_SSH_HOST="${UBUNTU_K3S_SSH_HOST:-ubuntu}"
export UBUNTU_K3S_SSH_USER="${UBUNTU_K3S_SSH_USER:-parallels}"
export UBUNTU_K3S_EXTERNAL_IP="${UBUNTU_K3S_EXTERNAL_IP:-10.211.55.14}"
export UBUNTU_K3S_REMOTE_KUBECONFIG="${UBUNTU_K3S_REMOTE_KUBECONFIG:-/home/parallels/.kube/k3s.yaml}"
export UBUNTU_K3S_LOCAL_KUBECONFIG="${UBUNTU_K3S_LOCAL_KUBECONFIG:-${HOME}/.kube/k3s-ubuntu.yaml}"
