apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/wilddog64/shopping-cart-payment//k8s/base?ref=main
patches:
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: payment-service
      imagePullSecrets:
        - name: ghcr-pull-secret
    target:
      kind: ServiceAccount
      name: payment-service
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: payment-service
      spec:
        template:
          spec:
            containers:
            - name: payment-service
              resources:
                requests:
                  cpu: 50m
    target:
      kind: Deployment
      name: payment-service
images:
  - name: ghcr.io/wilddog64/shopping-cart-payment
    digest: sha256:95f2680c4c192f66b6a4d9e17d4453b23c0dcaaf5a3dd8f22cbe104d322c14a4
