apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/wilddog64/shopping-cart-payment//k8s/base?ref=main
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: payment-service
      spec:
        template:
          spec:
            containers:
              - name: payment-service
                resources:
                  requests:
                    cpu: 100m
    target:
      kind: Deployment
      name: payment-service
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: payment-service
      imagePullSecrets:
        - name: ghcr-pull-secret
    target:
      kind: ServiceAccount
      name: payment-service
