# shellcheck shell=bash
# OCI Always Free (ARM64) — CLUSTER_PROVIDER=k3s-oci

OCI_COMPARTMENT_ID="${OCI_COMPARTMENT_ID:-}"
OCI_REGION="${OCI_REGION:-us-ashburn-1}"
OCI_AVAILABILITY_DOMAIN="${OCI_AVAILABILITY_DOMAIN:-}"
OCI_IMAGE_ID="${OCI_IMAGE_ID:-}"
OCI_INSTANCE_SHAPE="${OCI_INSTANCE_SHAPE:-VM.Standard.A1.Flex}"
OCI_OCPUS="${OCI_OCPUS:-2}"
OCI_MEMORY_GB="${OCI_MEMORY_GB:-12}"
OCI_SSH_KEY_FILE="${OCI_SSH_KEY_FILE:-${HOME}/.ssh/oci-k3s}"
OCI_K3S_VERSION="${OCI_K3S_VERSION:-v1.32.0+k3s1}"
OCI_CONTEXT="${OCI_CONTEXT:-k3s-oci}"
