controlPlane:
  statefulSet:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 1Gi
    persistence:
      volumeClaim:
        enabled: false
      dataVolume:
        - name: data
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
