apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: shopping-cart-apps
  labels:
    app.kubernetes.io/part-of: shopping-cart
    app.kubernetes.io/managed-by: argocd
    istio-injection: enabled
