apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/wilddog64/shopping-cart-product-catalog//k8s/base?ref=main
images:
  - name: ghcr.io/wilddog64/shopping-cart-product-catalog
    digest: sha256:b4b699519a7979e3797b9ac8d761774fa49bc0bafcea1acdd8929c78025bf4c2
patches:
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: product-catalog
      imagePullSecrets:
        - name: ghcr-pull-secret
    target:
      kind: ServiceAccount
      name: product-catalog
