apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/wilddog64/shopping-cart-product-catalog//k8s/base?ref=main
images:
  - name: ghcr.io/wilddog64/shopping-cart-product-catalog
    digest: sha256:e9bcb925619b5344a958fc359091b651c61365ce7b8a65c354408ee2f7198b92
patches:
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: product-catalog
      imagePullSecrets:
        - name: ghcr-pull-secret
    target:
      kind: ServiceAccount
      name: product-catalog
