# Keycloak configuration variables

# Namespace and Helm defaults
export KEYCLOAK_NAMESPACE="${KEYCLOAK_NAMESPACE:-identity}"
export KEYCLOAK_HELM_RELEASE="${KEYCLOAK_HELM_RELEASE:-keycloak}"
export KEYCLOAK_HELM_REPO_NAME="${KEYCLOAK_HELM_REPO_NAME:-bitnami}"
export KEYCLOAK_HELM_REPO_URL="${KEYCLOAK_HELM_REPO_URL:-https://charts.bitnami.com/bitnami}"
export KEYCLOAK_HELM_CHART_REF="${KEYCLOAK_HELM_CHART_REF:-bitnami/keycloak}"
export KEYCLOAK_HELM_CHART_VERSION="${KEYCLOAK_HELM_CHART_VERSION:-}"  # empty = latest

# Feature flags
export KEYCLOAK_LDAP_ENABLED="${KEYCLOAK_LDAP_ENABLED:-0}"
export KEYCLOAK_VAULT_ENABLED="${KEYCLOAK_VAULT_ENABLED:-0}"

# Istio / access configuration
export KEYCLOAK_VIRTUALSERVICE_HOST="${KEYCLOAK_VIRTUALSERVICE_HOST:-keycloak.dev.local.me}"
export KEYCLOAK_SERVICE_PORT="${KEYCLOAK_SERVICE_PORT:-8080}"
export KEYCLOAK_VIRTUALSERVICE_GATEWAY="${KEYCLOAK_VIRTUALSERVICE_GATEWAY:-istio-system/default-gateway}"

# Admin credentials
export KEYCLOAK_ADMIN_USERNAME="${KEYCLOAK_ADMIN_USERNAME:-admin}"
export KEYCLOAK_ADMIN_SECRET_NAME="${KEYCLOAK_ADMIN_SECRET_NAME:-keycloak-admin-secret}"
export KEYCLOAK_ADMIN_PASSWORD_KEY="${KEYCLOAK_ADMIN_PASSWORD_KEY:-password}"
export KEYCLOAK_VAULT_KV_MOUNT="${KEYCLOAK_VAULT_KV_MOUNT:-secret}"
export KEYCLOAK_ADMIN_VAULT_PATH="${KEYCLOAK_ADMIN_VAULT_PATH:-keycloak/admin}"

# LDAP integration
export KEYCLOAK_LDAP_SECRET_NAME="${KEYCLOAK_LDAP_SECRET_NAME:-keycloak-ldap-secret}"
export KEYCLOAK_LDAP_VAULT_PATH="${KEYCLOAK_LDAP_VAULT_PATH:-ldap/openldap-admin}"
export KEYCLOAK_LDAP_BINDDN_KEY="${KEYCLOAK_LDAP_BINDDN_KEY:-LDAP_BIND_DN}"
export KEYCLOAK_LDAP_PASSWORD_KEY="${KEYCLOAK_LDAP_PASSWORD_KEY:-LDAP_ADMIN_PASSWORD}"
export KEYCLOAK_LDAP_HOST="${KEYCLOAK_LDAP_HOST:-openldap-openldap-bitnami.identity.svc.cluster.local}"
export KEYCLOAK_LDAP_PORT="${KEYCLOAK_LDAP_PORT:-389}"
export KEYCLOAK_LDAP_BASE_DN="${KEYCLOAK_LDAP_BASE_DN:-dc=home,dc=org}"
export KEYCLOAK_LDAP_USERS_DN="${KEYCLOAK_LDAP_USERS_DN:-ou=users,dc=home,dc=org}"

# Realm configuration
export KEYCLOAK_REALM_NAME="${KEYCLOAK_REALM_NAME:-home}"
export KEYCLOAK_REALM_DISPLAY_NAME="${KEYCLOAK_REALM_DISPLAY_NAME:-Home}"

# ESO / Vault integration
export KEYCLOAK_ESO_SERVICE_ACCOUNT="${KEYCLOAK_ESO_SERVICE_ACCOUNT:-eso-keycloak-sa}"
export KEYCLOAK_ESO_SECRETSTORE="${KEYCLOAK_ESO_SECRETSTORE:-keycloak-vault-store}"
export KEYCLOAK_ESO_ROLE="${KEYCLOAK_ESO_ROLE:-eso-keycloak-admin}"
export KEYCLOAK_ESO_API_VERSION="${KEYCLOAK_ESO_API_VERSION:-external-secrets.io/v1}"
