#!/usr/bin/env bash
# scripts/plugins/acg.sh — ACG sandbox lifecycle management (credentials, extend, watch, teardown)
#
# Functions: acg_get_credentials acg_extend acg_watch acg_teardown acg_import_credentials
# AWS provisioning (acg_provision, acg_status): see scripts/plugins/aws.sh

if [[ -z "${SCRIPT_DIR:-}" ]]; then
  SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"
fi

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/plugins/aws.sh"
# shellcheck source=/dev/null
source "${SCRIPT_DIR}/plugins/antigravity.sh"

_ACG_SANDBOX_LIST_URL="${ACG_SANDBOX_LIST_URL:-https://app.pluralsight.com/hands-on/playground/cloud-sandboxes}"
_ACG_WATCH_PID_FILE="${HOME}/.local/share/k3d-manager/acg-watch.pid"
_ACG_WATCH_LAUNCHD_LABEL="com.k3d-manager.acg-watch"
_ACG_WATCH_PLIST_PATH="${HOME}/Library/LaunchAgents/${_ACG_WATCH_LAUNCHD_LABEL}.plist"
_ACG_WATCH_WRAPPER="${HOME}/.local/share/k3d-manager/acg-watch-run.sh"
_ACG_CHROME_CDP_LABEL="com.k3d-manager.chrome-cdp"
_ACG_CHROME_CDP_PLIST="${HOME}/Library/LaunchAgents/${_ACG_CHROME_CDP_LABEL}.plist"
_ACG_CHROME_CDP_AUTH_DIR="${HOME}/.local/share/k3d-manager/playwright-auth"
_ACG_CHROME_CDP_PORT=9222


_acg_watch_write_wrapper() {
  local sandbox_url="$1"
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  mkdir -p "$(dirname "${_ACG_WATCH_WRAPPER}")"
  cat > "${_ACG_WATCH_WRAPPER}" <<WRAPPER
#!/usr/bin/env bash
# Auto-generated by acg_watch_start — do not edit manually
set -euo pipefail
"${script_dir}/../k3d-manager" acg_extend_playwright "${sandbox_url}" \\
  || printf '[acg-watch] Extend failed — open %s to extend manually\\n' "${sandbox_url}" >&2
WRAPPER
  chmod +x "${_ACG_WATCH_WRAPPER}"
}

_acg_watch_write_plist() {
  mkdir -p "$(dirname "${_ACG_WATCH_PLIST_PATH}")"
  cat > "${_ACG_WATCH_PLIST_PATH}" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${_ACG_WATCH_LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${_ACG_WATCH_WRAPPER}</string>
  </array>
  <key>StartInterval</key>
  <integer>12600</integer>
  <key>StandardOutPath</key>
  <string>/tmp/k3d-manager-acg-watch.out</string>
  <key>StandardErrorPath</key>
  <string>/tmp/k3d-manager-acg-watch.err</string>
</dict>
</plist>
PLIST
}

_acg_chrome_cdp_write_plist() {
  mkdir -p "$(dirname "${_ACG_CHROME_CDP_PLIST}")"
  mkdir -p "${_ACG_CHROME_CDP_AUTH_DIR}"
  cat > "${_ACG_CHROME_CDP_PLIST}" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${_ACG_CHROME_CDP_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/Applications/Google Chrome.app/Contents/MacOS/Google Chrome</string>
    <string>--remote-debugging-port=${_ACG_CHROME_CDP_PORT}</string>
    <string>--user-data-dir=${_ACG_CHROME_CDP_AUTH_DIR}</string>
    <string>--password-store=basic</string>
    <string>--no-first-run</string>
    <string>--no-default-browser-check</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardErrorPath</key>
  <string>/tmp/k3d-manager-chrome-cdp.err</string>
</dict>
</plist>
PLIST
}

# Deprecated helper — use _aws_write_credentials instead
_acg_write_credentials() {
  _aws_write_credentials "$@"
}

# Deprecated alias — use aws_import_credentials instead
function acg_import_credentials() {
  aws_import_credentials "$@"
}

function _acg_browser_attach_or_launch() {
  local timeout="${1:-30}"
  
  if ! _command_exist curl; then
    _err "[acg] curl is required for browser CDP probe"
  fi

  # 1. Check if CDP is already responding
  if curl --noproxy "*" -sf http://127.0.0.1:9222/json >/dev/null 2>&1; then
    return 0
  fi

  # 2. If port is silent, check if Chrome is already running
  # Use -f to match the command line but exclude helpers/renderers
  if pgrep -f "Google Chrome.app/Contents/MacOS/Google Chrome" >/dev/null 2>&1; then
    _err "[acg] Google Chrome is running but CDP is not enabled on port 9222."
    _err "[acg] To use automation, you must restart Chrome with the debugging port enabled:"
    _err "[acg]   1. Quit Chrome completely (Cmd+Q)"
    _err "[acg]   2. Run: open -a \"Google Chrome\" --args --remote-debugging-port=9222"
    return 1
  fi

  # 3. Chrome not running at all — launch it with CDP enabled
  _info "[acg] Chrome not running — launching with --remote-debugging-port=9222..."
  if [[ "$(uname)" == "Darwin" ]]; then
    open -a "Google Chrome" --args \
      --remote-debugging-port=9222 \
      --password-store=basic \
      --user-data-dir="${HOME}/.config/acg-chrome-profile"
  else
    local _chrome_bin
    _chrome_bin=$(command -v google-chrome 2>/dev/null || command -v google-chrome-stable 2>/dev/null || command -v chromium-browser 2>/dev/null || command -v chromium 2>/dev/null || true)
    if [[ -z "${_chrome_bin}" ]]; then
      _err "[acg] Chrome/Chromium not found — install google-chrome or chromium"
    fi
    "${_chrome_bin}" \
      --remote-debugging-port=9222 \
      --password-store=basic \
      --user-data-dir="${HOME}/.config/acg-chrome-profile" &
  fi

  # Wait for port to become active
  local deadline=$(( $(date +%s) + timeout ))
  until curl -sf http://127.0.0.1:9222/json >/dev/null 2>&1; do
    if (( $(date +%s) >= deadline )); then
      _err "[acg] Timed out waiting for Chrome CDP on port 9222"
      return 1
    fi
    sleep 1
  done
  _info "[acg] Chrome CDP ready on port 9222"
  return 0
}

function acg_get_credentials() {
  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    cat <<HELP
Usage: acg_get_credentials [sandbox-url]

Extract AWS credentials from the Pluralsight Cloud Sandbox "Cloud Access" panel
via Chrome CDP (Playwright) and write to ~/.aws/credentials.

Requires Chrome running with --remote-debugging-port=9222. If Chrome is not
already running, it will be launched automatically.

Falls back to: pbpaste | acg_import_credentials

Arguments:
  sandbox-url   (optional) URL of a running sandbox, e.g.
                https://app.pluralsight.com/hands-on/playground/cloud-sandboxes/<id>
                Defaults to ACG_SANDBOX_LIST_URL (listing page — auto-start flow)
HELP
    return 0
  fi

  local sandbox_url="${1:-${_ACG_SANDBOX_LIST_URL}}"

  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  local playwright_script="${script_dir}/../playwright/acg_credentials.js"

  if ! command -v node >/dev/null 2>&1; then
    printf 'ERROR: %s\n' "[acg] node is required for Playwright automation — install Node.js" >&2
    return 1
  fi
  if ! node -e "require('playwright')" 2>/dev/null; then
    printf 'ERROR: %s\n' "[acg] playwright npm module not found — run: cd scripts/playwright && npm install" >&2
    return 1
  fi

  _acg_browser_attach_or_launch 30 || return 1

  _info "[acg] Extracting AWS credentials from ${sandbox_url}..."

  local output exit_code
  output=$(node "$playwright_script" "$sandbox_url" 2>&1)
  exit_code=$?

  case "${exit_code}" in
    0)
      _info "[acg] Credentials successfully extracted"
      ;;
    10)
      _err "[acg] Pluralsight session invalid or expired."
      _err "[acg]   1. Open Google Chrome"
      _err "[acg]   2. Sign in to Pluralsight manually"
      _err "[acg]   3. Rerun your command"
      return 1
      ;;
    11)
      _err "[acg] Attached to a non-sandbox browser page."
      _err "[acg] Please ensure the sandbox URL is correct and no security blocks are active."
      return 1
      ;;
    12)
      _err "[acg] Timed out waiting for sandbox credentials to populate."
      _err "[acg] The dashboard reached but expected elements did not appear."
      return 1
      ;;
    *)
      _err "[acg] Unexpected extraction failure (exit: ${exit_code})"
      _err "[acg] Log: ${output}"
      return 1
      ;;
  esac

  local access_key secret_key session_token
  access_key=$(printf '%s' "$output" | perl -ne 'if (/AWS_ACCESS_KEY_ID=(\S+)/) {print $1; exit}')
  secret_key=$(printf '%s' "$output" | perl -ne 'if (/AWS_SECRET_ACCESS_KEY=(\S+)/) {print $1; exit}')
  session_token=$(printf '%s' "$output" | perl -ne 'if (/AWS_SESSION_TOKEN=(\S+)/) {print $1; exit}')

  if [[ -z "$access_key" || -z "$secret_key" ]]; then
    _info "[acg] Playwright extraction failed — falling back to stdin paste"
    _info "[acg] Copy the credentials block from the Pluralsight sandbox page, then run:"
    _info "[acg]   pbpaste | ./scripts/k3d-manager acg_import_credentials"
    return 1
  fi

  _aws_write_credentials "$access_key" "$secret_key" "$session_token"
}


_acg_extend_playwright() {
  local sandbox_url="${1:?usage: _acg_extend_playwright <sandbox_url>}"

  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  local playwright_script="${script_dir}/../playwright/acg_extend.js"

  if ! command -v node >/dev/null 2>&1; then
    _err "[acg] node is required — install Node.js"
  fi

  _info "[acg] Extending ACG sandbox TTL at ${sandbox_url}..."
  local output exit_code
  output=$(node "$playwright_script" "$sandbox_url" 2>&1)
  exit_code=$?

  if [[ $exit_code -ne 0 ]]; then
    _info "[acg] acg_extend failed: ${output}"
    return 1
  fi

  echo "$output"
}

function acg_extend_playwright() {
  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    cat <<'HELP'
Usage: acg_extend_playwright <sandbox_url>

Extend the ACG sandbox TTL via Playwright automation.
Called by the launchd wrapper (acg_watch_start) and by acg_watch in-process.

Arguments:
  sandbox_url   Pluralsight sandbox URL (https://app.pluralsight.com/...)
HELP
    return 0
  fi
  _acg_extend_playwright "${@}"
}

function acg_extend() {
  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    cat <<'HELP'
Usage: acg_extend

Open the ACG Cloud Sandboxes page to extend the sandbox TTL (+4h).
On macOS, opens the URL in the default browser. On Linux, prints the URL.
HELP
    return 0
  fi

  _info "[acg] Opening ACG sandbox page to extend TTL..."
  _info "[acg] URL: ${_ACG_SANDBOX_URL}"
  if [[ "$(uname)" == "Darwin" ]]; then
    _run_command -- open "${_ACG_SANDBOX_URL}"
    _info "[acg] Click 'Extend Lab' on the sandbox page (+4h)"
  else
    _info "[acg] Open this URL in your browser and click 'Extend Lab':"
    _info "[acg] ${_ACG_SANDBOX_URL}"
  fi
}

function acg_watch() {
  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    cat <<'HELP'
Usage: acg_watch [interval_seconds]

Background sandbox TTL watcher. Extends the ACG sandbox every 3.5 hours
while the EC2 instance is alive. Stops automatically when the instance
is gone (after acg_teardown).

Default interval: 12600 seconds (3.5 hours).

Example (run after deploy_cluster):
  acg_watch &
  echo "Watcher PID: $!"
HELP
    return 0
  fi

  local interval="${1:-12600}"
  _info "[acg] Sandbox watcher started (PID $$, extending every $((interval / 3600))h)"

  while true; do
    sleep "$interval"
    if [[ -z "$(_acg_get_instance_id 2>/dev/null)" ]]; then
      _info "[acg] Instance gone — watcher stopping."
      return 0
    fi
    _info "[acg] Extending sandbox TTL..."
    _acg_extend_playwright "${_ACG_SANDBOX_URL}" \
      || _info "[acg] Extend failed — open ${_ACG_SANDBOX_URL} to extend manually"
  done
}

function acg_watch_start() {
  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    cat <<'HELP'
Usage: acg_watch_start [sandbox-url]

Install a launchd job that extends the ACG sandbox TTL every 3.5 hours,
independent of any terminal session or agent process.

macOS only. The job fires automatically at StartInterval=12600s and
persists across reboots until acg_watch_stop is called.

Arguments:
  sandbox-url   URL of the sandbox page (default: ACG_SANDBOX_LIST_URL)
HELP
    return 0
  fi

  if [[ "$(uname)" != "Darwin" ]]; then
    _info "[acg] acg_watch_start is macOS only — use acg_watch & on Linux"
    return 0
  fi

  local sandbox_url="${1:-${_ACG_SANDBOX_LIST_URL}}"

  _acg_watch_write_wrapper "$sandbox_url"
  _acg_watch_write_plist

  if launchctl list "${_ACG_WATCH_LAUNCHD_LABEL}" >/dev/null 2>&1; then
    _info "[acg] Reloading launchd job ${_ACG_WATCH_LAUNCHD_LABEL}..."
    launchctl unload "${_ACG_WATCH_PLIST_PATH}" 2>/dev/null || true
  fi

  launchctl load "${_ACG_WATCH_PLIST_PATH}"
  _info "[acg] Sandbox watcher installed: ${_ACG_WATCH_LAUNCHD_LABEL}"
  _info "[acg] Extends TTL every 3.5h — log: /tmp/k3d-manager-acg-watch.err"
}

function acg_watch_stop() {
  if [[ "$(uname)" != "Darwin" ]]; then
    _info "[acg] acg_watch_stop is macOS only"
    return 0
  fi

  if launchctl list "${_ACG_WATCH_LAUNCHD_LABEL}" >/dev/null 2>&1; then
    launchctl unload "${_ACG_WATCH_PLIST_PATH}" 2>/dev/null || true
    _info "[acg] Sandbox watcher stopped: ${_ACG_WATCH_LAUNCHD_LABEL}"
  else
    _info "[acg] Sandbox watcher not running"
  fi

  [[ -f "${_ACG_WATCH_PLIST_PATH}" ]] && rm -f "${_ACG_WATCH_PLIST_PATH}"
  [[ -f "${_ACG_WATCH_WRAPPER}" ]] && rm -f "${_ACG_WATCH_WRAPPER}"
}

function acg_chrome_cdp_install() {
  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    echo "Usage: acg_chrome_cdp_install"
    echo "Install a launchd agent that starts Chrome with CDP on port ${_ACG_CHROME_CDP_PORT}."
    echo "Chrome uses ${_ACG_CHROME_CDP_AUTH_DIR} as its profile (shared with Playwright scripts)."
    echo "Log: /tmp/k3d-manager-chrome-cdp.err"
    return 0
  fi

  if [[ "$(uname)" != "Darwin" ]]; then
    _info "[acg] acg_chrome_cdp_install is macOS only — skipping"
    return 0
  fi

  if [[ ! -f "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" ]]; then
    _err "[acg] Google Chrome not found at /Applications/Google Chrome.app — install Chrome first"
  fi

  _acg_chrome_cdp_write_plist

  if launchctl list "${_ACG_CHROME_CDP_LABEL}" >/dev/null 2>&1; then
    _info "[acg] Reloading Chrome CDP agent ${_ACG_CHROME_CDP_LABEL}..."
    launchctl unload "${_ACG_CHROME_CDP_PLIST}" 2>/dev/null || true
  fi

  launchctl load "${_ACG_CHROME_CDP_PLIST}"
  _info "[acg] Chrome CDP agent installed: ${_ACG_CHROME_CDP_LABEL}"
  _info "[acg] Chrome launches on login with --remote-debugging-port=${_ACG_CHROME_CDP_PORT}"
  _info "[acg] Profile: ${_ACG_CHROME_CDP_AUTH_DIR}"
  _info "[acg] Log: /tmp/k3d-manager-chrome-cdp.err"
  _info "[acg] Open http://localhost:${_ACG_CHROME_CDP_PORT} to verify CDP is active"
}

function acg_chrome_cdp_uninstall() {
  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    echo "Usage: acg_chrome_cdp_uninstall"
    echo "Unload and remove the Chrome CDP launchd agent."
    return 0
  fi

  if [[ "$(uname)" != "Darwin" ]]; then
    _info "[acg] acg_chrome_cdp_uninstall is macOS only — skipping"
    return 0
  fi

  if launchctl list "${_ACG_CHROME_CDP_LABEL}" >/dev/null 2>&1; then
    launchctl unload "${_ACG_CHROME_CDP_PLIST}" 2>/dev/null || true
    _info "[acg] Chrome CDP agent stopped: ${_ACG_CHROME_CDP_LABEL}"
  fi

  if [[ -f "${_ACG_CHROME_CDP_PLIST}" ]]; then
    rm -f "${_ACG_CHROME_CDP_PLIST}"
    _info "[acg] Plist removed: ${_ACG_CHROME_CDP_PLIST}"
  fi
}

function acg_teardown() {
  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    cat <<'HELP'
Usage: acg_teardown [--confirm]

Delete the ACG CloudFormation stack (VPC + SG + all EC2 instances) and
remove the ubuntu-k3s context from ~/.kube/config. The imported key pair
persists and is reused by subsequent acg_provision calls.

Requires --confirm to prevent accidental teardown.
HELP
    return 0
  fi

  if [[ "${1:-}" != "--confirm" ]]; then
    printf 'ERROR: %s\n' "[acg] acg_teardown requires --confirm to prevent accidental teardown" >&2
    return 1
  fi

  _acg_check_credentials || return 1

  local stack_status
  stack_status=$(_run_command --soft -- aws cloudformation describe-stacks \
    --region "${ACG_REGION}" --stack-name "${_ACG_CF_STACK_NAME}" \
    --query 'Stacks[0].StackStatus' --output text 2>/dev/null || true)

  if [[ -z "$stack_status" || "$stack_status" == "None" ]]; then
    _info "[acg] No CloudFormation stack found — nothing to tear down"
  else
    _info "[acg] Deleting CloudFormation stack ${_ACG_CF_STACK_NAME}..."
    _run_command -- aws cloudformation delete-stack \
      --region "${ACG_REGION}" --stack-name "${_ACG_CF_STACK_NAME}"
    _run_command -- aws cloudformation wait stack-delete-complete \
      --region "${ACG_REGION}" --stack-name "${_ACG_CF_STACK_NAME}"
    _info "[acg] Stack deleted"
  fi

  _info "[acg] Removing ubuntu-k3s context from kubeconfig..."
  if kubectl config get-contexts ubuntu-k3s >/dev/null 2>&1; then
    _run_command -- kubectl config delete-context ubuntu-k3s >/dev/null 2>&1 || true
    _info "[acg] Context ubuntu-k3s removed"
  fi

  _info "[acg] Teardown complete"
}
