export LDAP_NAMESPACE="${LDAP_NAMESPACE:-directory}"

export LDAP_PORT="${LDAP_PORT:-389}"
export LDAP_TLS="${LDAP_TLS:-636}"

export LDAP_REQ_CPU="${LDAP_REQ_CPU:-100m}"
export LDAP_REQ_MEM="${LDAP_REQ_MEM:-256Mi}"
export LDAP_LIMIT_MEM="${LDAP_LIMIT_MEM:-512Mi}"

export LDAP_DC_PRIMARY="${LDAP_DC_PRIMARY:-home}"
export LDAP_DC_SECONDARY="${LDAP_DC_SECONDARY:-org}"
export LDAP_BASE_DN="${LDAP_BASE_DN:-dc=${LDAP_DC_PRIMARY},dc=${LDAP_DC_SECONDARY}}"
export LDAP_ROOT="${LDAP_ROOT:-${LDAP_BASE_DN}}"
export LDAP_DOMAIN="${LDAP_DOMAIN:-${LDAP_DC_PRIMARY}.${LDAP_DC_SECONDARY}}"
export LDAP_GROUP_OU="${LDAP_GROUP_OU:-ou=groups}"
export LDAP_SERVICE_OU="${LDAP_SERVICE_OU:-ou=service}"
export LDAP_ORG_NAME="${LDAP_ORG_NAME:-Home Org}"

export LDAP_USERDN="${LDAP_USERDN:-${LDAP_SERVICE_OU},${LDAP_BASE_DN}}"
export LDAP_GROUPDN="${LDAP_GROUPDN:-${LDAP_GROUP_OU},${LDAP_BASE_DN}}"

export LDAP_HOST="${LDAP_HOST:-openldap.${LDAP_NAMESPACE}.svc.cluster.local}"
export LDAP_URL="${LDAP_URL:-ldap://${LDAP_HOST}:${LDAP_PORT}}"

export LDAP_BINDDN="${LDAP_BINDDN:-cn=ldap-admin,${LDAP_BASE_DN}}"
export LDAP_BINDPASS="${LDAP_BINDPASS:-}"

export LDAP_APP_ROLE="${LDAP_APP_ROLE:-ldap-reader}"
export LDAP_VAULT_PATH="${LDAP_VAULT_PATH:-ldap-ops}"

export LDAP_JENKINS_GROUP="${LDAP_JENKINS_GROUP:-jenkins-admins}"
export LDAP_JENKINS_USER="${LDAP_JENKINS_USER:-jenkins-bootstrap}"
export LDAP_JENKINS_USER_CN="${LDAP_JENKINS_USER_CN:-Jenkins Bootstrap}"
export LDAP_JENKINS_USER_SN="${LDAP_JENKINS_USER_SN:-Bootstrap}"
export LDAP_JENKINS_SERVICE_ACCOUNT_USERNAME="${LDAP_JENKINS_SERVICE_ACCOUNT_USERNAME:-jenkins-admin}"
export LDAP_JENKINS_SERVICE_ACCOUNT_GROUP="${LDAP_JENKINS_SERVICE_ACCOUNT_GROUP:-it develop}"
export LDAP_JENKINS_SERVICE_ACCOUNT_VAULT_PATH="${LDAP_JENKINS_SERVICE_ACCOUNT_VAULT_PATH:-ldap/service-accounts/jenkins-admin}"
export LDAP_JENKINS_SERVICE_ACCOUNT_USERNAME_KEY="${LDAP_JENKINS_SERVICE_ACCOUNT_USERNAME_KEY:-username}"
export LDAP_JENKINS_SERVICE_ACCOUNT_PASSWORD_KEY="${LDAP_JENKINS_SERVICE_ACCOUNT_PASSWORD_KEY:-password}"
export LDAP_JENKINS_SERVICE_ACCOUNT_GROUP_KEY="${LDAP_JENKINS_SERVICE_ACCOUNT_GROUP_KEY:-group_cn}"
export LDAP_JENKINS_SERVICE_ACCOUNT_POLICY="${LDAP_JENKINS_SERVICE_ACCOUNT_POLICY:-jenkins-ldap-service-account}"
export LDAP_JENKINS_SERVICE_ACCOUNT_DESCRIPTION="${LDAP_JENKINS_SERVICE_ACCOUNT_DESCRIPTION:-Jenkins LDAP service account}"

export LDAP_RELEASE="${LDAP_RELEASE:-openldap}"
export LDAP_IMAGE_REPOSITORY="${LDAP_IMAGE_REPOSITORY:-bitnamilegacy/openldap}"
export LDAP_IMAGE_TAG="${LDAP_IMAGE_TAG:-2.6.10-debian-12-r4}"
export LDAP_IMAGE_PULL_POLICY="${LDAP_IMAGE_PULL_POLICY:-Always}"
export LDAP_ADMIN_USERNAME="${LDAP_ADMIN_USERNAME:-ldap-admin}"
export LDAP_ADMIN_USERNAME_KEY="${LDAP_ADMIN_USERNAME_KEY:-LDAP_ADMIN_USERNAME}"
export LDAP_VAULT_KV_MOUNT="${LDAP_VAULT_KV_MOUNT:-secret}"
export LDAP_HELM_REPO_NAME="${LDAP_HELM_REPO_NAME:-johanneskastl-openldap-bitnami}"
export LDAP_HELM_REPO_URL="${LDAP_HELM_REPO_URL:-https://johanneskastl.github.io/openldap-bitnami-helm-chart/}"
export LDAP_HELM_CHART_REF="${LDAP_HELM_CHART_REF:-${LDAP_HELM_REPO_NAME}/openldap-bitnami}"
export LDAP_HELM_CHART_VERSION="${LDAP_HELM_CHART_VERSION:-1.5.3}"
export LDAP_HELM_CHART_ARCHIVE="${LDAP_HELM_CHART_ARCHIVE:-}"
export LDAP_HELM_REGISTRY_USERNAME="${LDAP_HELM_REGISTRY_USERNAME:-}"
export LDAP_HELM_REGISTRY_PASSWORD="${LDAP_HELM_REGISTRY_PASSWORD:-}"

export LDAP_ESO_SERVICE_ACCOUNT="${LDAP_ESO_SERVICE_ACCOUNT:-eso-ldap-sa}"
export LDAP_ESO_SECRETSTORE="${LDAP_ESO_SECRETSTORE:-vault-kv-store}"
export LDAP_ESO_ROLE="${LDAP_ESO_ROLE:-eso-ldap-directory}"
export LDAP_ADMIN_SECRET_NAME="${LDAP_ADMIN_SECRET_NAME:-openldap-admin}"
export LDAP_LDIF_SECRET_NAME="${LDAP_LDIF_SECRET_NAME:-openldap-bitnami-ldif-import}"
export LDAP_LDIF_ENABLED="${LDAP_LDIF_ENABLED:-true}"
export LDAP_LDIF_FILE="${LDAP_LDIF_FILE:-}"  # Path to custom LDIF file (optional)
export LDAP_LDIF_VAULT_PATH="${LDAP_LDIF_VAULT_PATH:-ldap/bootstrap}"
export LDAP_LDIF_CONTENT_KEY="${LDAP_LDIF_CONTENT_KEY:-content}"
export LDAP_LDIF_SECRET_KEY="${LDAP_LDIF_SECRET_KEY:-bootstrap.ldif}"
export LDAP_LDIF_REMOTE_PROPERTY="${LDAP_LDIF_REMOTE_PROPERTY:-content}"
export LDAP_LDIF_REFRESH_INTERVAL="${LDAP_LDIF_REFRESH_INTERVAL:-1h}"
export LDAP_VAULT_POLICY_PREFIX="${LDAP_VAULT_POLICY_PREFIX:-ldap}"
export LDAP_BASE_DN_KEY="${LDAP_BASE_DN_KEY:-LDAP_BASE_DN}"
export LDAP_BIND_DN_KEY="${LDAP_BIND_DN_KEY:-LDAP_BINDDN}"
export LDAP_DOMAIN_KEY="${LDAP_DOMAIN_KEY:-LDAP_DOMAIN}"
export LDAP_ROOT_KEY="${LDAP_ROOT_KEY:-LDAP_ROOT}"
export LDAP_ORG_NAME_KEY="${LDAP_ORG_NAME_KEY:-LDAP_ORG_NAME}"
if [[ -z "${LDAP_SKIP_DEFAULT_TREE:-}" ]]; then
   if [[ "${LDAP_LDIF_ENABLED:-false}" == "true" ]]; then
      export LDAP_SKIP_DEFAULT_TREE=true
   else
      export LDAP_SKIP_DEFAULT_TREE=false
   fi
fi
export LDAP_ADMIN_VAULT_PATH="${LDAP_ADMIN_VAULT_PATH:-ldap/openldap-admin}"
export LDAP_ADMIN_PASSWORD_KEY="${LDAP_ADMIN_PASSWORD_KEY:-LDAP_ADMIN_PASSWORD}"
export LDAP_CONFIG_PASSWORD_KEY="${LDAP_CONFIG_PASSWORD_KEY:-LDAP_CONFIG_PASSWORD}"
export LDAP_ESO_API_VERSION="${LDAP_ESO_API_VERSION:-external-secrets.io/v1}"
