# SSH tunnel configuration — override via env or this file
TUNNEL_SSH_HOST="${TUNNEL_SSH_HOST:-ubuntu}"
TUNNEL_LOCAL_PORT="${TUNNEL_LOCAL_PORT:-6443}"
TUNNEL_REMOTE_PORT="${TUNNEL_REMOTE_PORT:-6443}"
TUNNEL_BIND_ADDR="${TUNNEL_BIND_ADDR:-0.0.0.0}"
TUNNEL_LAUNCHD_LABEL="${TUNNEL_LAUNCHD_LABEL:-com.k3d-manager.ssh-tunnel}"
TUNNEL_PLIST_PATH="${TUNNEL_PLIST_PATH:-${HOME}/Library/LaunchAgents/${TUNNEL_LAUNCHD_LABEL}.plist}"
