apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"AppProject","metadata":{"annotations":{},"labels":{"managed-by":"k3d-manager","project-type":"platform"},"name":"platform","namespace":"argocd"},"spec":{"clusterResourceWhitelist":[{"group":"","kind":"Namespace"},{"group":"","kind":"PersistentVolume"},{"group":"rbac.authorization.k8s.io","kind":"ClusterRole"},{"group":"rbac.authorization.k8s.io","kind":"ClusterRoleBinding"},{"group":"apiextensions.k8s.io","kind":"CustomResourceDefinition"},{"group":"admissionregistration.k8s.io","kind":"MutatingWebhookConfiguration"},{"group":"admissionregistration.k8s.io","kind":"ValidatingWebhookConfiguration"},{"group":"networking.istio.io","kind":"Gateway"},{"group":"argoproj.io","kind":"Rollout"}],"description":"Platform services managed by k3d-manager","destinations":[{"namespace":"vault","server":"https://kubernetes.default.svc"},{"namespace":"jenkins","server":"https://kubernetes.default.svc"},{"namespace":"directory","server":"https://kubernetes.default.svc"},{"namespace":"istio-system","server":"https://kubernetes.default.svc"},{"namespace":"external-secrets-system","server":"https://kubernetes.default.svc"},{"namespace":"argocd","server":"https://kubernetes.default.svc"},{"namespace":"default","server":"https://kubernetes.default.svc"}],"namespaceResourceWhitelist":[{"group":"*","kind":"*"}],"orphanedResources":{"warn":true},"roles":[{"description":"Full admin access to platform project","groups":["platform-admins"],"name":"admin","policies":["p, proj:platform:admin, applications, *, platform/*, allow"]},{"description":"Developer access - sync and refresh only","groups":["platform-developers"],"name":"developer","policies":["p, proj:platform:developer, applications, get, platform/*, allow","p, proj:platform:developer, applications, sync, platform/*, allow"]}],"sourceRepos":["*"]}}
  creationTimestamp: "2025-12-09T02:06:23Z"
  generation: 1
  labels:
    managed-by: k3d-manager
    project-type: platform
  name: platform
  namespace: argocd
  resourceVersion: "1841299"
  uid: 0799f713-ec88-4883-8f2e-bc85d693a46d
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  - group: ""
    kind: PersistentVolume
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
  - group: networking.istio.io
    kind: Gateway
  - group: argoproj.io
    kind: Rollout
  description: Platform services managed by k3d-manager
  destinations:
  - namespace: vault
    server: https://kubernetes.default.svc
  - namespace: jenkins
    server: https://kubernetes.default.svc
  - namespace: directory
    server: https://kubernetes.default.svc
  - namespace: istio-system
    server: https://kubernetes.default.svc
  - namespace: external-secrets-system
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
  roles:
  - description: Full admin access to platform project
    groups:
    - platform-admins
    name: admin
    policies:
    - p, proj:platform:admin, applications, *, platform/*, allow
  - description: Developer access - sync and refresh only
    groups:
    - platform-developers
    name: developer
    policies:
    - p, proj:platform:developer, applications, get, platform/*, allow
    - p, proj:platform:developer, applications, sync, platform/*, allow
  sourceRepos:
  - '*'
