apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/wilddog64/shopping-cart-order//k8s/base?ref=main
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ghcr-pull-secret
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/httpGet/path
        value: /actuator/health
      - op: replace
        path: /spec/template/spec/containers/0/startupProbe
        value:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 30
    target:
      kind: Deployment
  - patch: |-
      - op: add
        path: /data/SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - op: add
        path: /data/SPRING_RABBITMQ_USERNAME
        value: guest
    target:
      kind: ConfigMap
      name: order-service-config
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: order-service
      spec:
        template:
          spec:
            containers:
            - name: order-service
              env:
              - name: SPRING_RABBITMQ_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: order-service-secrets
                    key: RABBITMQ_PASSWORD
    target:
      kind: Deployment
      name: order-service
