apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: k3dm-analyze
  namespace: cicd
  labels:
    release: kube-prometheus-stack
spec:
  route:
    receiver: k3dm-analyze
    matchers:
      - name: alertname
        value: ArgoCDAppDegraded|ArgoCDAppOutOfSync|TrivyOperatorScanJobFailures
        matchType: "=~"
  receivers:
    - name: k3dm-analyze
      webhookConfigs:
        - url: "https://webhook.3ai-talk.org/api/v1/analyze"
          httpConfig:
            authorization:
              type: Bearer
              credentials:
                name: k3dm-webhook-token
                key: token
