apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-cve-scanner
  namespace: platform-ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-cve-scanner
  namespace: cicd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-cve-scanner
  namespace: cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-cve-scanner
subjects:
  - kind: ServiceAccount
    name: argocd-cve-scanner
    namespace: platform-ops
