# jenkins/destinationrule.yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: jenkins
  namespace: jenkins
spec:
  host: jenkins.jenkins.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
