apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-admin
  namespace: jenkins
spec:
  refreshInterval: 168h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: jenkins-admin
    template:
      type: Opaque
      data:
        jenkins-admin-user: "{{ .username }}"
        jenkins-admin-password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef: { key: eso/jenkins-admin, property: username }
    - secretKey: password
      remoteRef: { key: eso/jenkins-admin, property: password }
