apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${JENKINS_ESO_SERVICE_ACCOUNT}
  namespace: ${JENKINS_NAMESPACE}
---
apiVersion: ${JENKINS_ESO_API_VERSION}
kind: SecretStore
metadata:
  name: ${JENKINS_ESO_SECRETSTORE}
  namespace: ${JENKINS_NAMESPACE}
spec:
  provider:
    vault:
      server: "${VAULT_ENDPOINT}"
      path: ${JENKINS_VAULT_KV_MOUNT}
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: ${JENKINS_ESO_ROLE}
          serviceAccountRef:
            name: ${JENKINS_ESO_SERVICE_ACCOUNT}
---
apiVersion: ${JENKINS_ESO_API_VERSION}
kind: ExternalSecret
metadata:
  name: ${JENKINS_ADMIN_SECRET_NAME}
  namespace: ${JENKINS_NAMESPACE}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ${JENKINS_ESO_SECRETSTORE}
    kind: SecretStore
  target:
    name: ${JENKINS_ADMIN_SECRET_NAME}
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ${JENKINS_ADMIN_K8S_USER_KEY}
      remoteRef:
        key: ${JENKINS_ADMIN_VAULT_PATH}
        property: ${JENKINS_ADMIN_USERNAME_KEY}
    - secretKey: ${JENKINS_ADMIN_K8S_PASS_KEY}
      remoteRef:
        key: ${JENKINS_ADMIN_VAULT_PATH}
        property: ${JENKINS_ADMIN_PASSWORD_KEY}
---
apiVersion: ${JENKINS_ESO_API_VERSION}
kind: ExternalSecret
metadata:
  name: ${JENKINS_LDAP_SECRET_NAME}
  namespace: ${JENKINS_NAMESPACE}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ${JENKINS_ESO_SECRETSTORE}
    kind: SecretStore
  target:
    name: ${JENKINS_LDAP_SECRET_NAME}
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: LDAP_BIND_DN
      remoteRef:
        key: ${JENKINS_LDAP_VAULT_PATH}
        property: ${JENKINS_LDAP_BINDDN_KEY}
    - secretKey: LDAP_BIND_PASSWORD
      remoteRef:
        key: ${JENKINS_LDAP_VAULT_PATH}
        property: ${JENKINS_LDAP_PASSWORD_KEY}
    - secretKey: LDAP_BASE_DN
      remoteRef:
        key: ${JENKINS_LDAP_VAULT_PATH}
        property: ${JENKINS_LDAP_BASE_DN_KEY}
