apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-helm
  namespace: ${ARGOCD_NAMESPACE}
  labels:
    managed-by: k3d-manager
    app-type: platform
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: dev
        values:
          revision: HEAD
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: '{{.name}}-platform'
      labels:
        cluster: '{{.name}}'
        environment: '{{.metadata.labels.environment}}'
    spec:
      project: platform
      destination:
        server: '{{.server}}'
        namespace: cicd
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
      source:
        repoURL: https://argoproj.github.io/argo-helm
        chart: argo-cd
        targetRevision: '{{.values.revision}}'
        helm:
          releaseName: argocd-{{.name}}
          parameters:
            - name: server.replicas
              value: "2"
            - name: repoServer.replicas
              value: "2"
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
