apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: cicd
data:
  registries.conf: |
    registries:
    - name: GitHub Container Registry
      api_url: https://ghcr.io
      prefix: ghcr.io
      credentials: pullsecret:shopping-cart-apps/ghcr-pull-secret
      defaultns: wilddog64
      insecure: false
