apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.3ai-talk.org"
      path: "secret"
      version: v2
      auth:
        kubernetes:
          mountPath: "kubernetes-app"
          role: "eso-app-cluster"
          serviceAccountRef:
            name: external-secrets
            namespace: secrets
